/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.diviso.graeshoppe.customerappgateway.client.administration.api;

import com.diviso.graeshoppe.customerappgateway.client.administration.model.FeedbackDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-01-27T14:13:06.209+05:30[Asia/Kolkata]")

@Api(value = "FeedbackResource", description = "the FeedbackResource API")
public interface FeedbackResourceApi {

    @ApiOperation(value = "createFeedback", nickname = "createFeedbackUsingPOST", notes = "", response = FeedbackDTO.class, tags={ "feedback-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FeedbackDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/feedbacks",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<FeedbackDTO> createFeedbackUsingPOST(@ApiParam(value = "feedbackDTO" ,required=true )  @Valid @RequestBody FeedbackDTO feedbackDTO);


    @ApiOperation(value = "deleteFeedback", nickname = "deleteFeedbackUsingDELETE", notes = "", tags={ "feedback-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/feedbacks/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteFeedbackUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllFeedbacks", nickname = "getAllFeedbacksUsingGET", notes = "", response = FeedbackDTO.class, responseContainer = "List", tags={ "feedback-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FeedbackDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/feedbacks",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<FeedbackDTO>> getAllFeedbacksUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getFeedback", nickname = "getFeedbackUsingGET", notes = "", response = FeedbackDTO.class, tags={ "feedback-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FeedbackDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/feedbacks/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<FeedbackDTO> getFeedbackUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchFeedbacks", nickname = "searchFeedbacksUsingGET", notes = "", response = FeedbackDTO.class, responseContainer = "List", tags={ "feedback-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FeedbackDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/feedbacks",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<FeedbackDTO>> searchFeedbacksUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateFeedback", nickname = "updateFeedbackUsingPUT", notes = "", response = FeedbackDTO.class, tags={ "feedback-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FeedbackDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/feedbacks",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<FeedbackDTO> updateFeedbackUsingPUT(@ApiParam(value = "feedbackDTO" ,required=true )  @Valid @RequestBody FeedbackDTO feedbackDTO);

}
