/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.diviso.graeshoppe.customerappgateway.client.administration.api;

import com.diviso.graeshoppe.customerappgateway.client.administration.model.RefundDetailsDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-01-27T14:13:06.209+05:30[Asia/Kolkata]")

@Api(value = "RefundDetailsResource", description = "the RefundDetailsResource API")
public interface RefundDetailsResourceApi {

    @ApiOperation(value = "createRefundDetails", nickname = "createRefundDetailsUsingPOST", notes = "", response = RefundDetailsDTO.class, tags={ "refund-details-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RefundDetailsDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/refund-details/{orderId}",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<RefundDetailsDTO> createRefundDetailsUsingPOST(@ApiParam(value = "orderId",required=true) @PathVariable("orderId") String orderId,@ApiParam(value = "refundDetailsDTO" ,required=true )  @Valid @RequestBody RefundDetailsDTO refundDetailsDTO);


    @ApiOperation(value = "deleteRefundDetails", nickname = "deleteRefundDetailsUsingDELETE", notes = "", tags={ "refund-details-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/refund-details/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteRefundDetailsUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllRefundDetails", nickname = "getAllRefundDetailsUsingGET", notes = "", response = RefundDetailsDTO.class, responseContainer = "List", tags={ "refund-details-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RefundDetailsDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/refund-details",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<RefundDetailsDTO>> getAllRefundDetailsUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getRefundDetails", nickname = "getRefundDetailsUsingGET", notes = "", response = RefundDetailsDTO.class, tags={ "refund-details-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RefundDetailsDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/refund-details/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<RefundDetailsDTO> getRefundDetailsUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchRefundDetails", nickname = "searchRefundDetailsUsingGET", notes = "", response = RefundDetailsDTO.class, responseContainer = "List", tags={ "refund-details-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RefundDetailsDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/refund-details",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<RefundDetailsDTO>> searchRefundDetailsUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateRefundDetails", nickname = "updateRefundDetailsUsingPUT", notes = "", response = RefundDetailsDTO.class, tags={ "refund-details-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = RefundDetailsDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/refund-details",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<RefundDetailsDTO> updateRefundDetailsUsingPUT(@ApiParam(value = "refundDetailsDTO" ,required=true )  @Valid @RequestBody RefundDetailsDTO refundDetailsDTO);

}
